### ISSUE TITLE
Revert SDK and TM to older versions due to IAVL pruning being enabled

### ISSUE THREAD

**Issue by jackzampolin** [cosmos/ethermint_bak#2]

**Comment by alexanderbez** [comment]
I maybe closing this due to us reverting back to not pruning by default until it becomes configurable: https://github.com/cosmos/cosmos-sdk/pull/1590

**Comment by cwgoes** [comment]
Should have been closed by https://github.com/cosmos/cosmos-sdk/pull/1590.
